wandb_version: 1

name:
  desc: null
  value: exp.csv
num_epochs:
  desc: null
  value: 15
norm:
  desc: null
  value: 0
lr:
  desc: null
  value: 5.0e-05
p_input:
  desc: null
  value: 0.5
scheduler:
  desc: null
  value: '{"def": "torch.optim.lr_scheduler.MultiStepLR", "params": {"milestones":
    [], "gamma": 0.1}}'
batch_size:
  desc: null
  value: 1024
momentum:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0
network:
  desc: null
  value: LogisticRegressor
dataset:
  desc: null
  value: csl
emg_tensorizer:
  desc: null
  value: CSLDataSegmentRMS
Trms:
  desc: null
  value: 75
adaptation:
  desc: null
  value: shift-adaptation
real_baseline:
  desc: null
  value: false
learnable_baseline:
  desc: null
  value: true
adabatch:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724777846
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
